OpenMind/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include, url
from perfiles.views import SignUpView, BienvenidaView, SignInView, SignOutView, ActualizarView, HechoView, TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^tipousuarios/', include(('apps.crud_tipousuario.urls', 'apps',), namespace='tipousuario')),
    url(r'^usuarios/', include(('apps.crud_datos_personales.urls', 'apps',), namespace='usuario')),
    url(r'^datosusuarios/', include(('apps.crud_datos_cuenta.urls', 'apps',), namespace='datosusuario')),
    url(r'^inteligencias/', include(('apps.crud_inteligencias.urls', 'apps',), namespace='inteligencias')),
    url(r'^cursos/', include(('apps.crud_curso.urls', 'apps',), namespace='cursos')),
    url(r'^temascursos/', include(('apps.crud_temas_curso.urls', 'apps',), namespace='temascursos')),
    url(r'^ejercicios/', include(('apps.crud_ejercicios.urls', 'apps',), namespace='ejercicios')),
    url(r'^cuestionario/', include(('apps.cuestionario.urls', 'apps',), namespace='cuestionario')),
    url(r'^distractorespregunta/', include(('apps.crud_distractores_preguntas.urls', 'apps',), namespace='distractorespregunta')),
    url(r'^preguntas/', include(('apps.crud_preguntas_test_inteligencia.urls', 'apps',), namespace='preguntastest')),

    #url(r'^admin/', admin.site.urls),
    url(r'^$', BienvenidaView.as_view(), name='bienvenida'),
    url(r'^registrarse/$', SignUpView.as_view(), name='sign_up'),
    url(r'^iniciar_sesion/$', SignInView.as_view(), name='sign_in'),
    url(r'^cerrar_sesion/$', SignOutView.as_view(), name='sign_out'),
    url(r'^registro_completado/$', view=TemplateView.as_view(template_name='registros/registro_nuevo.html'), name='registro'),

    url(r'^Acerca_de/$', view=TemplateView.as_view(template_name='about.html'), name='acerca_de'),

    url(r'^recuperar/contraseña/$', auth_views.PasswordResetView.as_view(
            template_name='registros/password_reset_form.html',
            html_email_template_name='registros/password_reset_email.html'
    ),      name='password_reset'),

    url(r'^recuperar/contraseña/hecho/$', auth_views.PasswordResetDoneView.as_view(
            template_name='registros/password_reset_done.html'
    ),      name='password_reset_done'),

    url(r'^recuperar/contraseña/(?P<uidb64>[0-9A-Za-z_\-]+)/'r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('password_reset_complete'),
            post_reset_login=True,
            template_name='registros/password_reset_confirm.html',
            post_reset_login_backend=('django.contrib.auth.backends.AllowAllUsersModelBackend'
                                      )),    name='password_reset_confirm'),

    url(r'^recuperar/contraseña/completo/$', auth_views.PasswordResetCompleteView.as_view(
            template_name='registros/password_reset_complete.html'
    ),      name='password_reset_complete'),


    url(r'^actualizar_contraseña/$', auth_views.PasswordChangeView.as_view(
        template_name='registros/password_change_form.html',
        success_url=reverse_lazy('password_change_done')),
        name='password_change'),

    url(r'^actualizar_contraseña_hecho/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registros/password_change_done.html'),
        name='password_change_done'),

    url(r'^email_change/$', login_required(TemplateView.as_view(template_name='registros/email_change_form.html')),
        name='email_change'),

    url(r'^editar_correo/$', ActualizarView.as_view(),
        name='cambiar_correo'),

    url(r'^editar_correo_done/$', HechoView.as_view(),
        name='cambiar_correo_hecho')


    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/crud_curso/urls.py
from django.conf.urls import url

from apps.crud_curso.views import cursoCreate, cursoList, cursoDelete, cursoUpdate, cursoShow, searchcurso, agregarcurso


urlpatterns = [
    url(r'^nuevo/$', cursoCreate.as_view(), name='cursocrear'),
    url(r'^listar/$', cursoList.as_view(), name='cursolistar'),
    url(r'^eliminar/(?P<pk>\d+)/$', cursoDelete.as_view(), name='cursoeliminar'),
    url(r'^editar/(?P<pk>\d+)/$', cursoUpdate.as_view(), name='cursoeditar'),
    url(r'^mostrar/(?P<pk>\d+)/$', cursoShow.as_view(), name='cursomostrar'),
    url(r'^buscar/$', searchcurso, name='cursobuscar'),
    url(r'^agregar/(?P<pk>\d+)/$', agregarcurso.as_view(), name='cursoagregar'),

        ]

apps/cuestionario/urls.py
from django.conf.urls import url
from apps.cuestionario.views import cuestionarioCreate,cuestionarioList, cuestionarioDelete, cuestionarioUpdate, cuestionarioShow, search

urlpatterns = [
    url(r'^nuevo/', cuestionarioCreate.as_view(), name='cuestionariocrear'),
    url(r'^listar/', cuestionarioList.as_view(), name='cuestionariolistar'),
    url(r'^eliminar/(?P<pk>\d+)/$', cuestionarioDelete.as_view(), name='cuestionarioeliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', cuestionarioUpdate.as_view(), name='cuestionarioeditar'),
    url(r'^mostrar/(?P<pk>\d+)/$', cuestionarioShow.as_view(), name='cuestionariomostrar'),
    url(r'^buscar/$', search, name='cuestionariobuscar'),
]

apps/cuestionario/models.py
from django.db import models

# Create your models here.

apps/cuestionario/forms.py
from django import forms
from apps.sistema.models import cuestionario

class CuestionarioForm(forms.ModelForm):
    class Meta:
        model = cuestionario
        fields = [
            'id_cuestionario',
            'id_pregunta_test',
            'resultado_pregunta_cuestionario'
        ]
        labels = {
            'id_cuestionario': 'Id',
            'id_pregunta_test': 'Pregunta',
            'resultado_pregunta_cuestionario': 'Valor'
        }

        widgets = {
            'id_cuestionario': forms.TextInput(attrs={'class': 'form-control'}),
            'id_pregunta_test': forms.Select(),
            'resultado_pregunta_cuestionario': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/cuestionario/views.py
# Create your views here.
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from apps.sistema.models import cuestionario
from apps.cuestionario.forms import CuestionarioForm
from apps.cuestionario.filters import cuestionarioFilter
from django.urls import reverse_lazy

class cuestionarioCreate(CreateView):
    model = cuestionario
    form_class = CuestionarioForm
    template_name = 'cuestionario/cuestionario_form.html'
    success_url = reverse_lazy('cuestionario:cuestionariobuscar')

class cuestionarioList(ListView):
    queryset = cuestionario.objects.order_by('id_cuestionario')
    template_name = 'cuestionario/cuestionario_list.html'
    paginate_by = 10

class cuestionarioUpdate(UpdateView):
    model = cuestionario
    form_class = CuestionarioForm
    template_name = 'cuestionario/cuestionario_form.html'
    success_url = reverse_lazy('cuestionario:cuestionariobuscar')

class cuestionarioDelete(DeleteView):
    model = cuestionario
    template_name = 'cuestionario/cuestionario_delete.html'
    success_url = reverse_lazy('cuestionario:cuestionariobuscar')

class cuestionarioShow(DetailView):
    model = cuestionario
    template_name = 'cuestionario/cuestionario_show.html'

def search(request):
    tipo_list = cuestionario.objects.all()
    tipo_filter = cuestionarioFilter(request.GET, queryset=tipo_list)
    return render(request, 'cuestionario/cuestionario_list_filter.html', {'filter': cuestionarioFilter})

templates/cuestionario/cuestionario_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.id_cuestionario }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'cuestionario:cuestionariobuscar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/cuestionario/cuestionario_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <!--div class="col s12 m12 l12"-->
            <div class="col-md-4 offset-md-4">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn purple" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'cuestionario:cuestionariobuscar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/cuestionario/cuestionario_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
            <thead>
            <tr>
                <td>Id Curso</td>
                <td>Nombre del Curso</td>
                <td>Nivel</td>
            </tr>
            </thead>
            <tbody>
            {% if object_list %}
                {% for curso in object_list %}
                    <tr>
                        <td>{{ curso.id_curso }}</td>
                        <td>{{ curso.nombre_curso }}</td>
                        <td>{{ curso.nivel }}</td>
                        <td>
                            <a class="btn brown" href="{% url 'cursos:cursomostrar' curso.id_curso %}"><i class="material-icons">zoom_in</i></a>
                            <a class="btn blue" href="{% url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">create</i></a>
                            <a class="btn red" href="{% url 'cursos:cursoeliminar' curso.id_curso %}"><i class="material-icons">delete</i></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <h1>No hay registros de curso</h1>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/cuestionario/cuestionario_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m8 l4">
        <h4>Buscar</h4>
        <form method="get">
            <div class="col s10 m10 l10">
                {{ filter.form.cuestionario }}
            </div>
            <div class="col s2 m2 l2">
                <button class="btn btn-success btn-large" name="Search" class="header-search-input z-depth-2" type="submit"><i class="large material-icons">search</i></button>
            </div>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <th width="10%">Id de cuestionario</th>
			        <th width="80%">Pregunta</th>
                    <th width="10%">Respuesta</th>
                </tr>
            </thead>
            <tbody>
		        {% if filter.qs %}
		        {% for cuestionario in filter.qs %}
		        <tr>
                    <td>{{ cuestionario.id_cuestionario }}</td>
			        <td>{{ cuestionario.id_pregunta_test }}</td>
                    <td>{{ cuestionario.resultado_pregunta_cuestionario }}</td>
			        <td>
                        <a class="btn-floating gradient-45deg-amber-amber" href="{% url 'cuestionario:cuestionariomostrar' cuestionario.id_cuestionario %}"><i class="material-icons">zoom_in</i></a>
                    </td>
                    <td>
				        <a class="btn-floating gradient-45deg-indigo-light-blue" href="{% url 'cuestionario:cuestionarioeditar' cuestionario.id_cuestionario %}"><i class="material-icons">create</i></a>
                    </td>
                    <td>
				        <a class="btn-floating red darken-4" href="{% url 'cuestionario:cuestionarioeliminar' cuestionario.id_cuestionario %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de resultados de cuestionarios</h1>
		    {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

    <div class="fixed-action-btn" style="width: 200px; height: 550px;">
        <a class="btn-floating btn-large gradient-45deg-deep-purple-blue tooltipped" data-position="top"  data-tooltip="Agregar curso" href="{% url 'cuestionario:cuestionariocrear' %}">
            <i class="large material-icons">mode_edit</i>
        </a>
    </div>

    <!--div class="fixed-action-btn">
        <a class="btn-floating btn-large red tooltipped" data-position="top" data-tooltip="Agregar" href="{% url 'cuestionario:cuestionariocrear' %}">
            <i class="large material-icons">add</i>
        </a>
    </div-->
 {% endblock%}

templates/cuestionario/cuestionario_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="table-bordered">
           <tr>
               <td width="15%">
                   <b>Id:</b>
               </td>
               <td>
                   {{ object.id_cuestionario }}
               </td>
           </tr>
            <tr>
               <td width="15%">
                   <b>Nombre del curso:</b>
               </td>
               <td>
                   {{ object.id_pregunta_test }}
               </td>
           </tr>
            <tr>
               <td width="15%">
                   <b>Nivel:</b>
               </td>
               <td>
                   {{ object.resultado_pregunta_cuestionario }}
               </td>
           </tr>
        </table>
        <p></p>

        <a class="btn-floating gradient-45deg-amber-amber tooltipped" data-position="top" data-tooltip="Ok" href="{% url 'cuestionario:cuestionariobuscar' %}"><i class="material-icons">check</i></a>
        <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cuestionario:cuestionarioeditar' object.id_cuestionario%}"><i class="material-icons">create</i></a>
        <a class="btn-floating red darken-4 tooltipped" data-position="top" data-tooltip="Borrar" href="{% url 'cuestionario:cuestionarioeliminar' object.id_cuestionario %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}