OpenMind/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include, url
from perfiles.views import SignUpView, BienvenidaView, SignInView, SignOutView, ActualizarView, HechoView, TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^tipousuarios/', include(('apps.crud_tipousuario.urls', 'apps',), namespace='tipousuario')),
    url(r'^usuarios/', include(('apps.crud_datos_personales.urls', 'apps',), namespace='usuario')),
    url(r'^datosusuarios/', include(('apps.crud_datos_cuenta.urls', 'apps',), namespace='datosusuario')),
    url(r'^inteligencias/', include(('apps.crud_inteligencias.urls', 'apps',), namespace='inteligencias')),
    url(r'^cursos/', include(('apps.crud_curso.urls', 'apps',), namespace='cursos')),
    url(r'^temascursos/', include(('apps.crud_temas_curso.urls', 'apps',), namespace='temascursos')),
    url(r'^ejercicios/', include(('apps.crud_ejercicios.urls', 'apps',), namespace='ejercicios')),
    url(r'^cuestionario/', include(('apps.cuestionario.urls', 'apps',), namespace='cuestionario')),
    url(r'^distractorespregunta/', include(('apps.crud_distractores_preguntas.urls', 'apps',), namespace='distractorespregunta')),
    url(r'^preguntas/', include(('apps.crud_preguntas_test_inteligencia.urls', 'apps',), namespace='preguntastest')),

    #url(r'^admin/', admin.site.urls),
    url(r'^$', BienvenidaView.as_view(), name='bienvenida'),
    url(r'^registrarse/$', SignUpView.as_view(), name='sign_up'),
    url(r'^iniciar_sesion/$', SignInView.as_view(), name='sign_in'),
    url(r'^cerrar_sesion/$', SignOutView.as_view(), name='sign_out'),
    url(r'^registro_completado/$', view=TemplateView.as_view(template_name='registros/registro_nuevo.html'), name='registro'),

    url(r'^Acerca_de/$', view=TemplateView.as_view(template_name='about.html'), name='acerca_de'),

    url(r'^recuperar/contraseña/$', auth_views.PasswordResetView.as_view(
            template_name='registros/password_reset_form.html',
            html_email_template_name='registros/password_reset_email.html'
    ),      name='password_reset'),

    url(r'^recuperar/contraseña/hecho/$', auth_views.PasswordResetDoneView.as_view(
            template_name='registros/password_reset_done.html'
    ),      name='password_reset_done'),

    url(r'^recuperar/contraseña/(?P<uidb64>[0-9A-Za-z_\-]+)/'r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('password_reset_complete'),
            post_reset_login=True,
            template_name='registros/password_reset_confirm.html',
            post_reset_login_backend=('django.contrib.auth.backends.AllowAllUsersModelBackend'
                                      )),    name='password_reset_confirm'),

    url(r'^recuperar/contraseña/completo/$', auth_views.PasswordResetCompleteView.as_view(
            template_name='registros/password_reset_complete.html'
    ),      name='password_reset_complete'),


    url(r'^actualizar_contraseña/$', auth_views.PasswordChangeView.as_view(
        template_name='registros/password_change_form.html',
        success_url=reverse_lazy('password_change_done')),
        name='password_change'),

    url(r'^actualizar_contraseña_hecho/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registros/password_change_done.html'),
        name='password_change_done'),

    url(r'^email_change/$', login_required(TemplateView.as_view(template_name='registros/email_change_form.html')),
        name='email_change'),

    url(r'^editar_correo/$', ActualizarView.as_view(),
        name='cambiar_correo'),

    url(r'^editar_correo_done/$', HechoView.as_view(),
        name='cambiar_correo_hecho')


    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/crud_datos_cuenta/urls.py
from django.conf.urls import url
from apps.crud_datos_cuenta.views import datosusuarioCreate, datosusuarioList, datosusuarioDelete, datosusuarioUpdate, datosusuarioShow, search

urlpatterns = [
    url(r'^nuevo/', datosusuarioCreate.as_view(), name='datosusuario_crear'),
    url(r'^listar/', datosusuarioList.as_view(),name='datosusuario_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', datosusuarioDelete.as_view(), name='datosusuario_eliminar'),
    url(r'^editar/(?P<pk>\d+)/$', datosusuarioUpdate.as_view(), name='datosusuario_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', datosusuarioShow.as_view(), name='datosusuario_mostrar'),
    url(r'^buscar/$', search, name='datosusuario_buscar'),
    ]

templates/datoscuenta/datoscuenta_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el usuario <b>{{ object.usuario }}</b>?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'datosusuario:datosusuario_buscar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/datoscuenta/datoscuenta_editar.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
    <h4>Editar usuario - {{ object.usuario }}</h4>
        <div class="col s12 m6 l3">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn purple" type="submit">Registrar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'datosusuario:datosusuario_buscar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/datoscuenta/datoscuenta_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
    <h4>Registrar usuario</h4>
        <div class="col s10 m6 l3">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn purple" type="submit">Registrar<i class="material-icons right">send</i></button> <br>
	            <br> <a class= "btn red" href="{% url 'datosusuario:datosusuario_buscar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
<hr />

     <!-- <div align="center" class="gradient-45deg-deep-purple-purple"> <a href="{% url 'sign_in' %}">Iniciar sesión</a></div> -->

{% endblock %}

templates/datoscuenta/datoscuenta_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
	        <thead>
		        <tr>
			        <th width="5%">Id de usuario</th>
			        <th width="80%">Usuario</th>
                    <th width="5%">Mostrar</th>
                    <th width="5%">Editar</th>
                    <th width="5%">Borrar</th>
                </tr>
            </thead>
            <tbody>
		        {% if object_list %}
		        {% for datoscuenta in object_list %}
		        <tr>
			        <td>{{ datoscuenta.id_usuario }}</td>
			        <td>{{ datoscuenta.usuario }}</td>
                    <td>
				         <a class="btn-floating gradient-45deg-amber-amber" href="{% url 'datosusuario:datosusuario_mostrar' datoscuenta.id_usuario %}"><i class="large material-icons">zoom_in</i></a>
                    </td>
                    <td>
				        <a class="btn-floating gradient-45deg-indigo-light-blue" href="{% url 'datosusuario:datosusuario_editar' datoscuenta.id_usuario %}"><i class="large material-icons">create</i></a>
                    </td>
                    <td>
				        <a class="btn-floating red darken-4" href="{% url 'datosusuario:datosusuario_eliminar' datoscuenta.id_usuario %}"><i class="large material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <tr>
                        <td colspan="10"><h1>No Existen Registros Personales</h1></td>
                    </tr>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/datoscuenta/datoscuenta_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
    <div align="center" class="col s12 m12 l12"> <h3>USUARIOS</h3></div>
    <div align="right" class="nav-wrapper container">
         <a href="{% url 'datosusuario:datosusuario_crear' %}" data-animation="top"><i class="material-icons" style="font-size: 50px">library_add</i><h6>Registrar</h6></a>
     </div>
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Buscar</h4>
        <form method="get">
            <div class="col s10 m10 l10">
                {{ filter.form.usuario }}
            </div>
            <div class="col s2 m2 l2">
                <button name="Search" class="header-search-input z-depth-2" type="submit"><i class="large material-icons">search</i></button>
            </div>
            <p>

             </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <th width="5%">Id de usuario</th>
			        <th width="80%">Usuario</th>
                    <th width="5%">Mostrar</th>
                    <th width="5%">Editar</th>
                    <th width="5%">Borrar</th>
                </tr>
            </thead>
            <tbody>
		        {% if filter.qs %}
		        {% for datoscuenta in filter.qs %}
		        <tr>
			        <td>{{ datoscuenta.id_usuario }}</td>
			        <td>{{ datoscuenta.usuario }}</td>
                    <td>
				         <a class="btn-floating gradient-45deg-amber-amber" href="{% url 'datosusuario:datosusuario_mostrar' datoscuenta.id_usuario %}"><i class="large material-icons">zoom_in</i></a>
                    </td>
                    <td>
				        <a class="btn-floating gradient-45deg-indigo-light-blue" href="{% url 'datosusuario:datosusuario_editar' datoscuenta.id_usuario %}"><i class="large material-icons">create</i></a>
                    </td>
                    <td>
				        <a class="btn-floating red darken-4" href="{% url 'datosusuario:datosusuario_eliminar' datoscuenta.id_usuario %}"><i class="large material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <tr>
                        <td colspan="10"><h1>No Existen Registros Personales</h1></td>
                    </tr>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>

    <!-- <h2>Área para miembros</h2>
<p>

    Bienvenido <b>{{request.user.username}}</b>,
                  {% if filter.qs %}
		        {% for datoscuenta in filter.qs %}
    Bienvenido <b>{{datoscuenta.usuario}}</b>,
    esta página es exclusiva para usuarios registrados.
</p>

                {% endfor %}

                {% else %}
		            <tr>
                        <td colspan="10"><h1>No Existen Registros Personales</h1></td>
                    </tr>
		        {% endif %}  -->

<hr />
<!-- <a href="/logout">Cerrar sesión</a>
    </div>
   <div class="fixed-action-btn">
        <a class="btn-floating btn-large red tooltipped" data-position="top" data-tooltip="Agregar" href="{% url 'datosusuario:datosusuario_crear' %}">
            <i class="large material-icons">add</i>
        </a>
    </div> -->
</div>
{% endblock %}

templates/datoscuenta/datoscuenta_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="table-bordered">
           <tr>
               <td width="15%">
                   <b>Id:</b>
               </td>
               <td>
                   {{ object.id_usuario }}
               </td>
           </tr>
            <tr>
               <td width="15%">
                   <b>Nombre de usuario:</b>
               </td>
               <td>
                   {{ object.usuario }}
               </td>
           </tr>
        </table>
        <p>

        </p>
        <a class="btn-floating gradient-45deg-amber-amber tooltipped" data-position="top" data-tooltip="Ok" href="{% url 'datosusuario:datosusuario_buscar' %}"><i class="material-icons">check</i></a>
        <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'datosusuario:datosusuario_editar' object.id_usuario%}"><i class="material-icons">create</i></a>
        <a class="btn-floating red darken-4 tooltipped" data-position="top" data-tooltip="Borrar" href="{% url 'datosusuario:datosusuario_eliminar' object.id_usuario %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/datoscuenta/login.html
<h2>Iniciar sesión</h2>

<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Login</button>
</form>

<hr />
<a href="/register">Registrar usuario</a>

templates/datoscuenta/register.html
<h2>Registrar usuario</h2>

<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Registrar</button>
</form>

<hr />

<a href="/login">Iniciar sesión</a>

templates/datoscuenta/welcome.html
<h2>Área para miembros</h2>

<p>
    Bienvenido <b>{{request.user.username}}</b>,
    esta página es exclusiva para usuarios registrados.
</p>

<hr />
<a href="/logout">Cerrar sesión</a>