OpenMind/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include, url
from perfiles.views import SignUpView, BienvenidaView, SignInView, SignOutView, ActualizarView, HechoView, TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^tipousuarios/', include(('apps.crud_tipousuario.urls', 'apps',), namespace='tipousuario')),
    url(r'^usuarios/', include(('apps.crud_datos_personales.urls', 'apps',), namespace='usuario')),
    url(r'^datosusuarios/', include(('apps.crud_datos_cuenta.urls', 'apps',), namespace='datosusuario')),
    url(r'^inteligencias/', include(('apps.crud_inteligencias.urls', 'apps',), namespace='inteligencias')),
    url(r'^cursos/', include(('apps.crud_curso.urls', 'apps',), namespace='cursos')),
    url(r'^temascursos/', include(('apps.crud_temas_curso.urls', 'apps',), namespace='temascursos')),
    url(r'^ejercicios/', include(('apps.crud_ejercicios.urls', 'apps',), namespace='ejercicios')),
    url(r'^cuestionario/', include(('apps.cuestionario.urls', 'apps',), namespace='cuestionario')),
    url(r'^distractorespregunta/', include(('apps.crud_distractores_preguntas.urls', 'apps',), namespace='distractorespregunta')),
    url(r'^preguntas/', include(('apps.crud_preguntas_test_inteligencia.urls', 'apps',), namespace='preguntastest')),

    #url(r'^admin/', admin.site.urls),
    url(r'^$', BienvenidaView.as_view(), name='bienvenida'),
    url(r'^registrarse/$', SignUpView.as_view(), name='sign_up'),
    url(r'^iniciar_sesion/$', SignInView.as_view(), name='sign_in'),
    url(r'^cerrar_sesion/$', SignOutView.as_view(), name='sign_out'),
    url(r'^registro_completado/$', view=TemplateView.as_view(template_name='registros/registro_nuevo.html'), name='registro'),

    url(r'^Acerca_de/$', view=TemplateView.as_view(template_name='about.html'), name='acerca_de'),

    url(r'^recuperar/contraseña/$', auth_views.PasswordResetView.as_view(
            template_name='registros/password_reset_form.html',
            html_email_template_name='registros/password_reset_email.html'
    ),      name='password_reset'),

    url(r'^recuperar/contraseña/hecho/$', auth_views.PasswordResetDoneView.as_view(
            template_name='registros/password_reset_done.html'
    ),      name='password_reset_done'),

    url(r'^recuperar/contraseña/(?P<uidb64>[0-9A-Za-z_\-]+)/'r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('password_reset_complete'),
            post_reset_login=True,
            template_name='registros/password_reset_confirm.html',
            post_reset_login_backend=('django.contrib.auth.backends.AllowAllUsersModelBackend'
                                      )),    name='password_reset_confirm'),

    url(r'^recuperar/contraseña/completo/$', auth_views.PasswordResetCompleteView.as_view(
            template_name='registros/password_reset_complete.html'
    ),      name='password_reset_complete'),


    url(r'^actualizar_contraseña/$', auth_views.PasswordChangeView.as_view(
        template_name='registros/password_change_form.html',
        success_url=reverse_lazy('password_change_done')),
        name='password_change'),

    url(r'^actualizar_contraseña_hecho/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registros/password_change_done.html'),
        name='password_change_done'),

    url(r'^email_change/$', login_required(TemplateView.as_view(template_name='registros/email_change_form.html')),
        name='email_change'),

    url(r'^editar_correo/$', ActualizarView.as_view(),
        name='cambiar_correo'),

    url(r'^editar_correo_done/$', HechoView.as_view(),
        name='cambiar_correo_hecho')


    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/crud_ejercicios/urls.py
from django.conf.urls import url

from apps.crud_ejercicios.views import ejerciciosCreate, ejerciciosList, ejerciciosDelete, ejerciciosUpdate, ejerciciosShow, searchejercicios

urlpatterns = [
    url(r'^nuevo/', ejerciciosCreate.as_view(), name='ejercicioscrear'),
    url(r'^listar/', ejerciciosList.as_view(), name='ejercicioslistar'),
    url(r'^eliminar/(?P<pk>\d+)/$', ejerciciosDelete.as_view(), name='ejercicioseliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', ejerciciosUpdate.as_view(), name='ejercicioseditar'),
    url(r'^mostrar/(?P<pk>\d+)/$', ejerciciosShow.as_view(), name='ejerciciosmostrar'),
    url(r'^buscar/$', searchejercicios, name='ejerciciosbuscar'),
]

apps/crud_preguntas_test_inteligencia/urls.py
from django.conf.urls import url

from apps.crud_preguntas_test_inteligencia.views import preguntas_test_inteligenciaCreate, preguntas_test_inteligenciaList, preguntas_test_inteligenciaDelete, preguntas_test_inteligenciaUpdate, preguntas_test_inteligenciaShow, searchpreguntas

urlpatterns = [
    url(r'^nuevo/', preguntas_test_inteligenciaCreate.as_view(), name='preguntascrear'),
    url(r'^listar/', preguntas_test_inteligenciaList.as_view(), name='preguntaslistar'),
    url(r'^eliminar/(?P<pk>\d+)/$', preguntas_test_inteligenciaDelete.as_view(), name='preguntaseliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', preguntas_test_inteligenciaUpdate.as_view(), name='preguntaseditar'),
    url(r'^mostrar/(?P<pk>\d+)/$', preguntas_test_inteligenciaShow.as_view(), name='preguntasmostrar'),
    url(r'^buscar/$', searchpreguntas, name='preguntasbuscar'),
]

templates/ejercicios/ejercicios_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el ejercicio <b>{{ object.nombre_ejercicio }}</b> del tema <b>{{ object.temas_curso }}</b>?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'ejercicios:ejerciciosbuscar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/ejercicios/ejercicios_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <!--div class="col s12 m8 l4"-->
        <div class="col-md-4 offset-md-4">
            <h3 align="center">Ejercicio nuevo</h3>
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn btn-primary" type="submit">Guardar<i class="material-icons right">send</i></button> &nbsp; &nbsp; &nbsp; &nbsp;
	            <a class= "btn btn-danger" href="{% url 'ejercicios:ejercicioslistar'%}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/ejercicios/ejercicios_list.html
{% extends 'base/base.html' %}

{% block content %}

<div class="row">
        <div class="col-sm-12"> <h3 align="center">Sección ejercicios</h3>

 <div class="fixed-action-btn" style="width: 200px; height: 550px;">
        <a class="btn-floating btn-large gradient-45deg-deep-purple-blue tooltipped" data-position="top"  data-tooltip="Agregar ejercicio" href="{% url 'ejercicios:ejercicioscrear' %}">
            <i class="large material-icons">mode_edit</i>
        </a>
    </div>

      <h4>Buscar</h4> <br>
            <form method="get" action="{% url 'ejercicios:ejerciciosbuscar' %}">
           <div class="col s6 m6 l6">
            Nombre de curso: &nbsp {{ filter.form.nombre_ejercicio }}
               </div>
            <div class="col s2 m2 l2">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </div>
            </form>
        </div>
    </div>
            {% if object_list %}
		        {% for ejercicios in object_list %}
<div class="row">
    <div class="col-md-4 offset-md-4">
            <div class="card gradient-45deg-blue-grey-blue">
                <div class="card-content white-text">

                    <span class="card-title"> <b>{{ejercicios.nombre_ejercicio }}</b></span>
                    <!--p>ID: { ejercicios.id_ejercicio }} </p-->
                    <p><b> Puntaje: </b> {{ ejercicios.puntaje }} </p>
                    <p><b> Tema: </b> {{ ejercicios.temas_curso }} </p>
                    <!--div class="card-action">
                    </div-->

                </div>
                    <div class="card-action">
                    <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Ver" href="{% url 'ejercicios:ejerciciosmostrar' ejercicios.id_ejercicio %}"><i class="material-icons">zoom_in</i> </a>
                    <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'ejercicios:ejercicioseditar' ejercicios.id_ejercicio %}"><i class="material-icons">create</i></a>
                    <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'ejercicios:ejercicioseliminar' ejercicios.id_ejercicio %}"><i class="material-icons">delete</i></a>
               </div>


        </div>
    </div>
</div>
        {% endfor %}
                {% else %}
		            <br> <br> <br> <h2>No hay registros de ejercicios</h2>
                {% endif %}

    {% if is_paginated %}
     <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination justify-content-center">

                {% if page_obj.has_previous %}
       	        <li class="waves-effect">

       	            <a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        </li>
                {% endif %}

                {% for i in paginator.page_range %}
                <li {% if page_obj.number == i %} class="active" {% endif %}>
                    <a href="?page={{ i }}" class="page-item">{{ i }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
     	        <li class="waves-effect">
     	            <a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        </li>
                {% endif %}

            </ul>
        </div>
    </div>
        {% endif %}

{% endblock%}

templates/ejercicios/ejercicios_list_filter.html
{% extends 'base/base.html' %}

 {% block content %}
<div class="row">
        <div class="col-sm-12"> <h3 align="center">Buscar preguntas</h3>

 <div class="fixed-action-btn" style="width: 200px; height: 550px;">
        <a class="btn-floating btn-large gradient-45deg-deep-purple-blue tooltipped" data-position="top"  data-tooltip="Agregar pregunta" href="{% url 'preguntastest:preguntascrear' %}">
            <i class="large material-icons">mode_edit</i>
        </a>
    </div>

<h4>Buscar</h4> <br>
    <form method="get" action="{% url 'preguntastest:preguntasbuscar' %}">
        <div class="col s6 m6 l6">
            Nombre de curso: &nbsp {{ filter.form.nombre_ejercicio}}
         </div>
            <div class="col s2 m2 l2">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </div>
            </form>
        </div>
    </div>
            {% if filter.qs %}
		        {% for ejercicios in filter.qs %}
<div class="row">
    <div class="col-md-4 offset-md-4">
            <div class="card gradient-45deg-blue-grey-blue">
                <div class="card-content white-text">

                    <span class="card-title"> <b>{{ ejercicios.nombre_ejercicio }}</b></span>
                    <!--p>ID: { ejercicios.id_ejercicio }} </p-->
                    <p><b> Puntaje:</b> {{ ejercicios.puntaje }} </p>
                    <p><b> Tema:</b> {{ ejercicios.temas_curso }} </p>
                    <!--div class="card-action">
                    </div-->

                </div>
                     <div class="card-action">
                    <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Ver" href="{% url 'ejercicios:ejerciciosmostrar' ejercicios.id_ejercicio %}"><i class="material-icons">zoom_in</i> </a>
                    <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'ejercicios:ejercicioseditar' ejercicios.id_ejercicio %}"><i class="material-icons">create</i></a>
                    <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'ejercicios:ejercicioseliminar' ejercicios.id_ejercicio %}"><i class="material-icons">delete</i></a>
               </div>


        </div>
    </div>
</div>
                {% endfor %}
                {% else %}
		            <br> <br> <br> <h2>No hay registros de ejercicios</h2>
                {% endif %}

 {% endblock%}

templates/ejercicios/ejercicios_show.html
{% extends 'base/base.html' %}

{% block content %}

<div class="row">
     <div class="col-sm-12"> <h3 align="center">Sección Ejercicios</h3>
        </div>
    </div>

<div class="row">
    <div class="col-md-4 offset-md-4">
            <div class="card gradient-45deg-blue-indigo">
                <div class="card-content white-text">

                    <span class="card-title"> <b>{{ object.nombre_ejercicio }}</b></span>
                    <p>ID: {{ object.id_ejercicio }} </p>
                    <p>No. pregunta: {{ object.puntaje }} </p>
                    <p>Tipo de Inteligencia: {{ object.temas_curso }} </p>
                    <!--div class="card-action">
                    </div-->

                </div>
                    <div class="card-action">
                        <a class="btn-floating gradient-45deg-amber-amber tooltipped" data-position="top" data-tooltip="Ok" href="{% url 'ejercicios:ejercicioslistar' %}"><i class="material-icons">check</i></a>
                        <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'ejercicios:ejercicioseditar' object.id_ejercicio %}"><i class="material-icons">create</i></a>
                        <a class="btn-floating red darken-4 tooltipped" data-position="top" data-tooltip="Borrar" href="{% url 'ejercicios:ejercicioseliminar' object.id_ejercicio %}"><i class="material-icons">delete</i></a>
                    </div>
        </div>
    </div>
</div>



{% endblock %}