OpenMind/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include, url
from perfiles.views import SignUpView, BienvenidaView, SignInView, SignOutView, ActualizarView, HechoView, TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^tipousuarios/', include(('apps.crud_tipousuario.urls', 'apps',), namespace='tipousuario')),
    url(r'^usuarios/', include(('apps.crud_datos_personales.urls', 'apps',), namespace='usuario')),
    url(r'^datosusuarios/', include(('apps.crud_datos_cuenta.urls', 'apps',), namespace='datosusuario')),
    url(r'^inteligencias/', include(('apps.crud_inteligencias.urls', 'apps',), namespace='inteligencias')),
    url(r'^cursos/', include(('apps.crud_curso.urls', 'apps',), namespace='cursos')),
    url(r'^temascursos/', include(('apps.crud_temas_curso.urls', 'apps',), namespace='temascursos')),
    url(r'^ejercicios/', include(('apps.crud_ejercicios.urls', 'apps',), namespace='ejercicios')),
    url(r'^cuestionario/', include(('apps.cuestionario.urls', 'apps',), namespace='cuestionario')),
    url(r'^distractorespregunta/', include(('apps.crud_distractores_preguntas.urls', 'apps',), namespace='distractorespregunta')),
    url(r'^preguntas/', include(('apps.crud_preguntas_test_inteligencia.urls', 'apps',), namespace='preguntastest')),

    #url(r'^admin/', admin.site.urls),
    url(r'^$', BienvenidaView.as_view(), name='bienvenida'),
    url(r'^registrarse/$', SignUpView.as_view(), name='sign_up'),
    url(r'^iniciar_sesion/$', SignInView.as_view(), name='sign_in'),
    url(r'^cerrar_sesion/$', SignOutView.as_view(), name='sign_out'),
    url(r'^registro_completado/$', view=TemplateView.as_view(template_name='registros/registro_nuevo.html'), name='registro'),

    url(r'^Acerca_de/$', view=TemplateView.as_view(template_name='about.html'), name='acerca_de'),

    url(r'^recuperar/contraseña/$', auth_views.PasswordResetView.as_view(
            template_name='registros/password_reset_form.html',
            html_email_template_name='registros/password_reset_email.html'
    ),      name='password_reset'),

    url(r'^recuperar/contraseña/hecho/$', auth_views.PasswordResetDoneView.as_view(
            template_name='registros/password_reset_done.html'
    ),      name='password_reset_done'),

    url(r'^recuperar/contraseña/(?P<uidb64>[0-9A-Za-z_\-]+)/'r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('password_reset_complete'),
            post_reset_login=True,
            template_name='registros/password_reset_confirm.html',
            post_reset_login_backend=('django.contrib.auth.backends.AllowAllUsersModelBackend'
                                      )),    name='password_reset_confirm'),

    url(r'^recuperar/contraseña/completo/$', auth_views.PasswordResetCompleteView.as_view(
            template_name='registros/password_reset_complete.html'
    ),      name='password_reset_complete'),


    url(r'^actualizar_contraseña/$', auth_views.PasswordChangeView.as_view(
        template_name='registros/password_change_form.html',
        success_url=reverse_lazy('password_change_done')),
        name='password_change'),

    url(r'^actualizar_contraseña_hecho/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registros/password_change_done.html'),
        name='password_change_done'),

    url(r'^email_change/$', login_required(TemplateView.as_view(template_name='registros/email_change_form.html')),
        name='email_change'),

    url(r'^editar_correo/$', ActualizarView.as_view(),
        name='cambiar_correo'),

    url(r'^editar_correo_done/$', HechoView.as_view(),
        name='cambiar_correo_hecho')


    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/crud_curso/urls.py
from django.conf.urls import url

from apps.crud_curso.views import cursoCreate, cursoList, cursoDelete, cursoUpdate, cursoShow, searchcurso, agregarcurso


urlpatterns = [
    url(r'^nuevo/$', cursoCreate.as_view(), name='cursocrear'),
    url(r'^listar/$', cursoList.as_view(), name='cursolistar'),
    url(r'^eliminar/(?P<pk>\d+)/$', cursoDelete.as_view(), name='cursoeliminar'),
    url(r'^editar/(?P<pk>\d+)/$', cursoUpdate.as_view(), name='cursoeditar'),
    url(r'^mostrar/(?P<pk>\d+)/$', cursoShow.as_view(), name='cursomostrar'),
    url(r'^buscar/$', searchcurso, name='cursobuscar'),
    url(r'^agregar/(?P<pk>\d+)/$', agregarcurso.as_view(), name='cursoagregar'),

        ]

templates/curso/curso_add.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="table-bordered">
           <tr>
               <td width="15%">
                   <b>Id:</b>
               </td>
               <td>
                   {{ object.id_curso }}
               </td>
           </tr>
            <tr>
               <td width="15%">
                   <b>Nombre del curso:</b>
               </td>
               <td>
                   {{ object.nombre_curso }}
               </td>
           </tr>
            <tr>
               <td width="15%">
                   <b>Nivel:</b>
               </td>
               <td>
                   {{ object.nivel }}
               </td>
           </tr>
        </table>
        <p></p>

        <a class="btn-floating gradient-45deg-amber-amber tooltipped" data-position="top" data-tooltip="OK" href="{% url 'cursos:cursolistar' %}"><i class="material-icons">check</i></a>
        <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cursos:cursoeditar' object.id_curso%}"><i class="material-icons">create</i></a>
        <a class="btn-floating red darken-4 tooltipped" data-position="top" data-tooltip="Borrar" href="{% url 'cursos:cursoeliminar' object.id_curso %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/curso/curso_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de <b>{{ object.nombre_curso }}?</b></h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'cursos:cursolistar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/curso/curso_editar.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-md-5 offset-md-3">
        <h4>EDITAR CURSO - <b> {{ object.nombre_curso }}</b></h4>
        <!--div class="col s12 m8 l4"-->
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn gradient-45deg-green-teal" type="submit">Guardar<i class="material-icons right">send</i></button> &nbsp; &nbsp; &nbsp; &nbsp;
	            <a class= "btn red" href="{% url 'cursos:cursolistar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/curso/curso_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <!--div class="col s12 m8 l4"-->
            <div class="col-md-4 offset-md-4">
                <h4 align="center"><b> NUEVO CURSO </b></h4>
            <form method="post" enctype="multipart/form-data">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn gradient-45deg-green-teal" type="submit">Guardar<i class="material-icons right">send</i></button>  &nbsp; &nbsp; &nbsp; &nbsp;
	            <a class= "btn gradient-45deg-red-pink" href="{% url 'cursos:cursolistar' %}">Cancelar<i class="material-icons right">cancel</i></a>
              </form>
            </div>
    </div>
{% endblock %}

templates/curso/curso_list.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_authenticated %}

<div class="row">
        <div class="col-sm-12"> <h3 align="center">CURSOS DISPONIBLES</h3>

                    <!--div class="carousel">
    <a class="carousel-item" href="#" style="font-size: larger"><img src="/static/img2/poo.jpg"></a>
    <a class="carousel-item" href="#two!"><img src="/static/img2/po/poo.png"></a>
    <a class="carousel-item" href="#three!"><img src="/static/img2/po/poo1.png"></a>
    <a class="carousel-item" href="#four!"><img src="/static/img2/po/poo2.png"></a>
    <a class="carousel-item" href="#five!"><img src="/static/img2/po/poo3.png"></a>
  </div-->


 <div class="fixed-action-btn" style="width: 200px; height: 550px;">
        <a class="btn-floating btn-large gradient-45deg-deep-purple-blue tooltipped" data-position="top"  data-tooltip="Agregar curso" href="{% url 'cursos:cursocrear' %}">
            <i class="large material-icons">mode_edit</i>
        </a>
    </div>

      <h4>Buscar</h4> <br>
        <form method="get" action="{% url 'cursos:cursobuscar' %}">
           <div class="col s6 m6 l6">
            <!-- <div class="col s10 m8 l8"> -->
               <!--div class="col s8 m8 offset-m2 l8 offset-13"-->
            Nombre de curso: &nbsp {{ filter.form.nombre_curso }}
               </div>
            <div class="col s2 m2 l2">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            <!--button class="btn blue btn-large" name="Search" class="header-search-input -depth-2" type="submit"><i class="large material-icons">search</i></button-->
            </div>
        </form>
        </div>
    </div>

    <!--ul>
  % if filter.qs %}
      % for curso in filter.qs %}
      <li> { curso.nombre_curso }}</li>
    % endfor %}
  % else %}
    <li>Sorry, no hay re in this list.</li>
  % endif %}
</ul-->

                        {% if object_list %}
                        {% for curso in object_list %}

<div class="row">
    <div class="col-md-4 offset-md-4">
            <!--div class="card blue lighten-5"-->
            <div class="card gradient-45deg-blue-indigo">
                <div class="card-content white-text">
                    <span class="card-title"> <b>{{ curso.nombre_curso }}</b></span>
                    <!--img style="width: 100%" src="{ curso.image.url }}"-->
                    <p>Nivel: {{ curso.nivel }} </p>
                    <!--div class="card-action">
                        <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Seleccionar" href="{% url 'cursos:cursoagregar' curso.id_curso %}"><i class="material-icons">add</i> </a>
                    </div-->

                </div>
                    <div class="card-action">
                    <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Ver" href="{% url 'cursos:cursomostrar' curso.id_curso %}"><i class="material-icons">zoom_in</i> </a>
                    <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">create</i></a>
                    <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'cursos:cursoeliminar' curso.id_curso %}"><i class="material-icons">delete</i></a>
               </div>


        </div>
    </div>
</div>
        {% endfor %}
                {% else %}
		            <br> <br> <br> <h2>No hay registros de curso en esta lista</h2>
                {% endif %}

{% if is_paginated %}
     <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination justify-content-center">

                {% if page_obj.has_previous %}
       	        <li class="waves-effect">
       	            <a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        </li>
                {% endif %}

                {% for i in paginator.page_range %}
                <li {% if page_obj.number == i %} class="active" {% endif %}>
                    <a href="?page={{ i }}" class="page-item">{{ i }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
     	        <li class="waves-effect">
     	            <a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        </li>
                {% endif %}

            </ul>
        </div>
    </div>
{% endif %}

    {% else %}
    {% endif %}

{% endblock%}

templates/curso/curso_list_filter.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_authenticated %}

<div class="row">
      <div class="col-sm-12"> <h3 align="center"> BUSCAR CURSOS</h3>

<!--div align="center" class="nav-wrapper container">
    <a href=" % url 'cursos:cursocrear' %}"><i class="material-icons" style="font-size: 45px">library_add</i><h6>Agregar Curso</h6></a></div-->

 <div class="fixed-action-btn" style="width: 200px; height: 550px;">
        <a class="btn-floating btn-large gradient-45deg-deep-purple-blue tooltipped" data-position="top"  data-tooltip="Agregar curso" href="{% url 'cursos:cursocrear' %}">
            <i class="large material-icons">mode_edit</i>
        </a>
    </div>


      <h4>Buscar</h4> <br>
        <form method="get">
           <div class="col s6 m6 l6">
            <!-- <div class="col s10 m8 l8"> -->
               <!--div class="col s8 m8 offset-m2 l8 offset-13"-->
            Nombre de curso: &nbsp {{ filter.form.nombre_curso }}
               </div>
            <div class="col s2 m2 l2">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            <!--button class="btn blue btn-large" name="Search" class="header-search-input -depth-2" type="submit"><i class="large material-icons">search</i></button-->
            </div>
        </form>
        </div>
    </div>

    {% if filter.qs %}
        {% for curso in filter.qs %}

<div class="row">
    <!--div class="col-sm-6"-->
         <!--div class="col s12 m6"-->
      <div class="col-md-4 offset-md-4">
            <div class="card gradient-45deg-green-teal">
                <div class="card-content white-text">
                    <span class="card-title"><b>{{ curso.nombre_curso }}</b></span>
                    <img src="{{ curso.image.url }}" style="width: 100%">
                    <p>Nivel: {{ curso.nivel }} </p>

                </div>
                    <div class="card-action">
                    <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Ver" href="{% url 'cursos:cursomostrar' curso.id_curso %}"><i class="material-icons">zoom_in</i></a>
                    <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">edit</i></a>
                    <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'cursos:cursoeliminar' curso.id_curso %}"><i class="material-icons">delete</i></a>
               </div>
        </div>
    </div>
  <!--/div-->
</div>
            <!--div class="card gradient-45deg-blue-grey-blue">
                <div class="card-content white-text">
                    <span class="card-title"> <b>{ curso.nombre_curso }}</b> </span>
                    <br> <p>Nivel: { curso.nivel }}
                            ID: { curso.id_curso }}</p> <br>
                    <!--div class="card-action">
                    <a class="btn-floating gradient-45deg-deep-purple-blue tooltipped" data-position="top" data-tooltip="Seleccionar" href="{% url 'cursos:cursoagregar' curso.id_curso %}"><i class="material-icons">add</i> </a>
                    </div-->
                <!--/div>
                    <div class="card-action">
                    <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Ver" href="{% url 'cursos:cursomostrar' curso.id_curso %}"><i class="material-icons">zoom_in</i> </a>
                    <a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">create</i></a>
                    <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'cursos:cursoeliminar' curso.id_curso %}"><i class="material-icons">delete</i></a>
               </div>
        </div>
    </div>
  </div-->
        {% endfor %}
                {% else %}
		            <br> <br> <br> <h2>No hay registros de Curso</h2>
                {% endif %}

<!--% if is_paginated %}
    <body class = "container">
      <div class = "row" style = "width:560px;">
         <div class = "col s12 m12 l12" >
            <h5>Materialize Pagination</h5>
            <ul class = "pagination justify-content-center">
                % if page_obj.has_previous %}
                    <li class="active"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
		        % endif %}

                % for i in paginator.page_range %}
                <li class="waves-effect" % if page_obj.number == i %} class="active" % endif %}>
                    <a href="?page={{ i }}" class="page-link">{{ i }}></a>
                </li>
                % endfor %}

		        % if page_obj.has_next %}
                    <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
    	        % endif %}
            </ul>
         </div>
      </div>
   </body>
    % endif %}

    <ul class="pagination">
    <li class="disabled"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="?page={{ i }}">2</a></li>
    <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
  </ul-->

    {% else %}
    {% endif %}

{% endblock %}

templates/curso/curso_show.html
{% extends 'base/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-image">
          <img style="width: 100%;" src="{{ curso.image.url }}">

          <a class="btn-floating btn-large halfway-fab waves-effect waves-light gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="Editar" href="{% url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">create</i></a>
        </div>
        <div class="card-content">
            <span class="card-title"><b>{{ curso.nombre_curso }}</b></span>
       <p>
           <a class="btn-floating gradient-45deg-green-teal tooltipped" data-position="top" data-tooltip="OK" href="{% url 'cursos:cursolistar' %}"><i class="material-icons">check</i></a> &nbsp;&nbsp; &nbsp; &nbsp;
           <!--a class="btn-floating gradient-45deg-indigo-light-blue tooltipped" data-position="top" data-tooltip="Editar" href=" url 'cursos:cursoeditar' curso.id_curso %}"><i class="material-icons">create</i></a-->
           <a class="btn-floating gradient-45deg-red-pink tooltipped" data-position="top" data-tooltip="Eliminar" href="{% url 'cursos:cursoeliminar' curso.id_curso %}"><i class="material-icons">delete</i></a>
       </p> <!--p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p-->
        </div>
      </div>
    </div>
</div>

{% endblock %}